version: '2'
services:
  fabric:
    image: rascov/docker-fabric
    privileged: true
    environment:
      - FABRIC_SPINE=2  # Number of spine switches
      - FABRIC_LEAF=2   # Number of leaf switches
      - FABRIC_FANOUT=2 # Number of hosts per leaf
      - FABRIC_CONTROLLER=$OC1,$OC2,$OC3,$OC4,$OC5,$OC6,$OC7 # Comma-separated controller IP address
